services:
  service:
    build: 
      context: .
      dockerfile: Dockerfile.service
    environment:
      CHOKIDAR_USEPOLLING: 1
      CARGO_TARGET_DIR: /tmp/target
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    volumes:
      - ../apps/service:/app
      - saml_sample_cargo_cache:/usr/local/cargo/registry
      - saml_sample_target_cache:/tmp/target
    ports:
      - 3000:3000
    tty: true
    working_dir: /app
    security_opt:
      - seccomp:unconfined
      
  keyclock:
    image: keycloak/keycloak
    ports:
      - 18080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin


volumes:
  saml_sample_cargo_cache:
  saml_sample_target_cache:
